### ISSUE TITLE
Only permit targeting minor versions of StableHLO (not patch versions)

### ISSUE THREAD

**Issue by GleasonK** [openxla/stablehlo#1653]
### Request description

For forward compatibility, only permit targeting `X.Y.0` (patch version 0) releases of StableHLO. This will help ensure that our forward and backward compatibility tests are exhaustive. See discussion [here](https://github.com/openxla/stablehlo/pull/1498#discussion_r1199852128) for details.

**Comment by abhigunj** [comment]
after discussing with  @GleasonK   decided to close this ticket with following rationale. 

1. User wants to serialize for their current version, typically not patch v0.
2. Using PjRT, we are a producer at HEAD, communicating with a plugin compiled in the past, asking for the plugin's StableHLO opset version, also unlikely to be patch v0.
3. We are serializing based on a compatibility requirement (i.e. version from 1 month ago), this use case tends to use patch v0 since it is more explicit with providing the version string.

Given that (1) and (2) are common use cases that are growing in popularity, we will continue to support specifying patch version targets

**Comment by abhigunj** [comment]
pending documentation
