### ISSUE TITLE
Consider verifying `channel_type` to default to zero when not used

### ISSUE THREAD

**Issue by ghpvnist** [openxla/stablehlo#1733]
As pointed out in https://github.com/openxla/stablehlo/pull/1731#discussion_r1293885176, the `channel_type` value is lost when [roundtripping](https://github.com/openxla/xla/blob/4ed4ae233a904df1d0b085a654ecb162632b401f/xla/translate/hlo_to_mhlo/hlo_function_importer.cc#L2202) to MHLO.

**Comment by burmako** [comment]
channel_type is intentionally not part of the StableHLO spec for collective ops, because it is ignored by XlaBuilder. Here's an example from XlaBuilder::ReduceScatter ([link](https://github.com/tensorflow/tensorflow/blob/4c40c3991e4a71f4819c22f24f4f580893ea121e/tensorflow/compiler/xla/client/xla_builder.cc#L3389-L3391)). This is working as intended.
