### ISSUE TITLE
stablehlo.uniform_quantize cannot be serialized to bytecode

### ISSUE THREAD

**Issue by lsy323** [openxla/stablehlo#1812]
### What happened?

The MLIR module containing `stablehlo.uniform_quantize/dequantize` ops failed during bytecode serializing with error
```
loc("custom-call.6"): error: failed to legalize operation 'stablehlo.uniform_quantize' that was explicitly marked illegal
```

However, the MLIR module can be serialized to readable format
```
module @IrToHlo.18 attributes {mhlo.cross_program_prefetches = [], mhlo.is_dynamic = false, mhlo.use_auto_spmd_partitioning = false} {
  func.func @main(%arg0: tensor<10xf32>, %arg1: tensor<10x3x3x3xf32>, %arg2: tensor<1x3x10x10xf32>) -> tensor<1x10x8x8xf32> {
    %0 = stablehlo.constant dense<0.000000e+00> : tensor<1x10x8x8xf32>
    %1 = stablehlo.uniform_quantize %arg2 : (tensor<1x3x10x10xf32>) -> tensor<1x3x10x10x!quant.uniform<i8:f32, 1.000000e+00>>
    %2 = stablehlo.uniform_dequantize %1 : (tensor<1x3x10x10x!quant.uniform<i8:f32, 1.000000e+00>>) -> tensor<1x3x10x10xf32>
    %3 = stablehlo.uniform_quantize %arg1 : (tensor<10x3x3x3xf32>) -> tensor<10x3x3x3x!quant.uniform<i8<-127:127>:f32, 1.000000e+00>>
    %4 = stablehlo.uniform_dequantize %3 : (tensor<10x3x3x3x!quant.uniform<i8<-127:127>:f32, 1.000000e+00>>) -> tensor<10x3x3x3xf32>
    %5 = stablehlo.convolution(%2, %4) dim_numbers = [b, f, 0, 1]x[o, i, 0, 1]->[b, f, 0, 1], window = {stride = [1, 1], pad = [[0, 0], [0, 0]], lhs_dilate = [1, 1], rhs_dilate = [1, 1], reverse = [0, 0]} {batch_group_count = 1 : i64, feature_group_count = 1 : i64, precision_config = [#stablehlo<precision DEFAULT>, #stablehlo<precision DEFAULT>]} : (tensor<1x3x10x10xf32>, tensor<10x3x3x3xf32>) -> tensor<1x10x8x8xf32>
    %6 = stablehlo.broadcast_in_dim %arg0, dims = [1] : (tensor<10xf32>) -> tensor<1x10x8x8xf32>
    %7 = stablehlo.add %5, %6 : tensor<1x10x8x8xf32>
    %8 = stablehlo.maximum %7, %0 : tensor<1x10x8x8xf32>
    %9 = stablehlo.uniform_quantize %8 : (tensor<1x10x8x8xf32>) -> tensor<1x10x8x8x!quant.uniform<i8:f32, 1.000000e+00>>
    %10 = stablehlo.uniform_dequantize %9 : (tensor<1x10x8x8x!quant.uniform<i8:f32, 1.000000e+00>>) -> tensor<1x10x8x8xf32>
    return %10 : tensor<1x10x8x8xf32>
  }
}
```

### Steps to reproduce your issue

The StableHLO with uniform_quant/dequant op is generated from PyTorch -> PyTorch/XLA -> StableHLO. To reproduce the bug e2e requires changes in PyTorch/XLA and HLO->StableHLO converter. The change hasn't been merged to PyTorch/XLA head.(But will be merged soon as experimental feature) Please let me if repro e2e is needed.

[This function](https://github.com/pytorch/xla/blob/8f45caefb4f6012af78c167893017f812f8103f9/torch_xla/csrc/runtime/stablehlo_helper.cc#L40-L48) is used to serialize stablehlo bytecode in PyTorch/XLA

### Version information

StableHLO commit 46a2506405a0c1ade5327b9e476a32781221b075

from openxla/xla: 51b59cfb1999c6f1b3ec59851675044b2c502aae

**Comment by lsy323** [comment]
cc @GleasonK

**Comment by GleasonK** [comment]
Thanks for reporting! Will take a look early next week.

**Comment by arfaian** [comment]
Hey @GleasonK, any update on this issue? We're currently using a workaround for this that we'd like to get rid of.

**Comment by sdasgup3** [comment]
The issue is related to propagation of signless information for integer storage type during PyTorch to StableHLO export. 

StableHLO, as bootstrapped from MHLO, inherits signless integers which was added in MHLO for some legacy reasons. Because of that signless integers are treated as signed.

During PyTorch --> HLO export,
we create signed integer (e.g. `si8`) (from [here](https://github.com/pytorch/xla/blob/8217c6b5cea304f74c3b508eabcc06fd1e125f42/torch_xla/csrc/quant_util.cpp#L48) and  [here](https://github.com/pytorch/xla/blob/8217c6b5cea304f74c3b508eabcc06fd1e125f42/torch_xla/csrc/runtime/stablehlo_helper.cc#L173)) as storage type and store in in the attribute string dictionary. 

During HLO --> Stablehlo,
we create a signed integer as the storage type of `UniformQuantizedType` ([here](https://github.com/pytorch/xla/blob/8217c6b5cea304f74c3b508eabcc06fd1e125f42/openxla_patches/quant_dequant_converter.diff#L75)).

During StableHLO -> VHLO, we do not convert such signed type ([cs](https://github.com/openxla/stablehlo/blob/a96c816c8bf5fc9aecfa88323aa1e73560e48dd4/stablehlo/dialect/VhloTypes.cpp#L29)), following the rational that only signless integers are considered to be signed integer unless https://github.com/openxla/stablehlo/issues/22 is resolved. 

Note that this issue was not reproduced when we serialize using a string format of an in-memory representation  mainly because `si8` in a Stablehlo in in-memory module representation is pretty printed as `i8` which can be serialized w/o any issue. 

My proposal is for PyTorch -> StableHLO export to generate signless integers for storage type. Here is the propotype of the proposal: https://github.com/pytorch/xla/pull/6613

**Comment by sdasgup3** [comment]
@lsy323 Can you please check if the proposal https://github.com/pytorch/xla/pull/6613 works with your setup before I sent it for PR review.

**Comment by GleasonK** [comment]
Any status update here? Reassigning to Sandeep who will have a better idea on how to triage (or perhaps https://github.com/pytorch/xla/pull/6613 should mark this as fixed on submit)?

**Comment by sdasgup3** [comment]
Per suggestion from @lsy323, we will review+land https://github.com/pytorch/xla/pull/6613  once the ci is clean.

**Comment by lsy323** [comment]
Thanks @sdasgup3! Issue resolved in https://github.com/pytorch/xla/pull/6613
