### ISSUE TITLE
broadcast_in_dim specification does not say anything about the order of broadcasted_dimensions

### ISSUE THREAD

**Issue by bchetioui** [openxla/stablehlo#2066]
### What happened?

The [broadcast_in_dim specification](https://github.com/openxla/stablehlo/blob/main/docs/spec.md#broadcast_in_dim) does not seem to state anything about the expected order of `broadcasted_dimensions`, and the given example on the page (reproduced below) seems to allow dimensions to be provided in arbitrary orders.

```
%result = "stablehlo.broadcast_in_dim"(%operand) {
  broadcast_dimensions = array<i64: 2, 1>
} : (tensor<1x3xi32>) -> tensor<2x3x2xi32>
```

I think however that [XLA expects those dimensions to be sorted in increasing order](https://openxla.org/xla/broadcasting#formal_definition), and that [JAX likewise requires dimensions sorted in increasing order for its broadcast_in_dim_p primitive](https://github.com/google/jax/blob/28fa88681edbeedc4ed86e46b38ca7b380a0c4c6/jax/_src/lax/lax.py#L2970-L2973). Sorting also makes more sense to me, otherwise your broadcast has also become a transpose.

Given that the example is explicitly broadcasting with "reversed" broadcasting dimensions, I'm not sure if this is intentional or an oversight---hence I'm filing this bug :)

**Comment by sdasgup3** [comment]
The example here is intentional and demonstrates the fact that `broadcast_dimensions` allows adding dimensions anywhere in the result shape.

Actually, the specification is similar to what we have in XLA https://openxla.org/xla/operation_semantics#broadcastindim where `broadcast_dimensions` maps the dimensions of operand to the dimensions of the target shape, i.e. the i'th dimension of the operand is mapped to the broadcast_dimension[i]'th dimension of the output shape.

Please let me know if this helps.

**Comment by bchetioui** [comment]
Thanks for the explanation! I'm not entirely sure I understand the rationale for supporting also unsorted broadcast dimensions. (Is anyone actually using that? As we both saw above, XLA and JAX definitely don't.)

Regardless, I see this is a point where StableHLO has decided to take a different path and this is thus not an oversight. Thanks again Sandeep, I'll close this now.
