### ISSUE TITLE
"Dialect `stablehlo` not found for custom op" when using python API

### ISSUE THREAD

**Issue by kilianyp** [openxla/stablehlo#2072]
### What happened?

*** mlir._mlir_libs._site_initialize.<locals>.MLIRError: Unable to parse module assembly:
error: "-":3:10: Dialect `stablehlo' not found for custom op 'stablehlo.dot_general' 
 note: "-":3:10: Registered dialects: acc, affine, amdgpu, amx, arith, arm_neon, arm_sme, arm_sve, async, bufferization, builtin, cf, complex, dlti, emitc, func, gpu, index, irdl, linalg, llvm, math, memref, mesh, ml_program, mpi, nvgpu, nvvm, omp, pdl, pdl_interp, quant, rocdl, scf, shape, sparse_tensor, spirv, tensor, tosa, transform, ub, vcix, vector, x86vector ; for more info on dialect registration see https://mlir.llvm.org/getting_started/Faq/#registered-loaded-dependent-whats-up-with-dialects-management

### Steps to reproduce your issue

1. install python wheel:  pip install stablehlo -f https://github.com/openxla/stablehlo/releases/expanded_assets/dev-wheels

```python
import jax
from mlir.ir import Module, Context
import mlir.dialects.stablehlo

a = jax.numpy.array([15, 12, 11])
b = jax.numpy.array([17, 12, 10])

def matmul(x, y):
    return (x @ y.T)

out = matmul(a, b)

data_info = jax.ShapeDtypeStruct((3,), dtype=jax.numpy.dtype("int32"))

jit = jax.jit(matmul).lower(data_info, data_info)
stable_hlo = jit.as_text("stablehlo")
print(stable_hlo)
with Context() as context:
    module = Module.parse(stable_hlo, context)
```

The import for ```import mlir.dialects.stablehlo``` works fine

### Version information

stablehlo                0.18.4.1709533290+c2fccec9

**Comment by kilianyp** [comment]
I found a solution:
```python
import jax
from mlir.ir import Module, Context
import mlir.dialects.stablehlo as shlo

a = jax.numpy.array([15, 12, 11])
b = jax.numpy.array([17, 12, 10])

def matmul(x, y):
    return (x @ y.T)

out = matmul(a, b)

data_info = jax.ShapeDtypeStruct((3,), dtype=jax.numpy.dtype("int32"))

jit = jax.jit(matmul).lower(data_info, data_info)
stable_hlo = jit.as_text("stablehlo")
print(stable_hlo)
with Context() as context:
    shlo.register_dialect(context)
    module = Module.parse(stable_hlo, context)
```

I'd still be interested to know how much of a focus this will be for stableHLO

**Comment by GleasonK** [comment]
> how much of a focus this will be for stableHLO

Could you clarify what "this" means here? I'm interpreting it a few ways:

1. How important is being able to easily extract StableHLO from frameworks - JAX, PT, TF?
Very important, we're working on clear documentation for how to do this now.
2. How important are the python bindings?
Also fairly important, JAX functions by directly using these bindings to build the StableHLO graph
3. How important are exposing graph rewrite machinery in the Python API?
This isn't something we're actively working on, but if some functionality is important to members of our community (and we are aware of it) we have no intention of breaking it. Best suggestion would be to add a test case to the repo which exercises the types of things you are interested in so we know we aren't breaking important features.

**Comment by vincent-mayer** [comment]
Related to your link to [stablehlo.md](https://github.com/pytorch/xla/blob/master/docs/stablehlo.md):
Torch-xla (somehow) adds sharding annotations to the StabeHLO program. Do you have a pointer to where/how this is happening? The intent behind the question is to understand the best/desired way to add custom attributes to the StableHLO export. 

On the other hand the way torch-xla adds these annotations for sharding does not seem to be the desired use-case, quoting the [spec.md](https://github.com/openxla/stablehlo/blob/main/docs/spec.md):

> At the moment, StableHLO programs in the wild sometimes contain attributes which are not described in this document. In the future, we are planning to either absorb these attributes into the StableHLO opset or prohibit them from appearing in StableHLO programs.

**Comment by GleasonK** [comment]
> > we are planning to either absorb these attributes into the StableHLO opset or prohibit them from appearing in StableHLO programs.

> I.e. is it even at all intended for users to add custom attributes or would this go too much into the custom MLIR dialect direction?

I don't think we'll ever fully get rid of unregistered attributes. This would inhibit experimentation too much IMO, and that section was written long ago. I will say, our goal is to standardize _as much as possible_, so that programs are more hardware agnostic. If unregistered attrs alter semantics, then only the subset of HW that knows about the attr can support the program, however much we can limit this problem, the better.

> The intent behind the question is to understand the best/desired way to add custom attributes to the StableHLO export.

I'm not sure about best, since there are many existing approaches that are used in practice - also want to note that StableHLO at its core is just MLIR, so "a good MLIR solution" would be the same, and searching for MLIR solutions can be helpful.

1. Use Python APIs to add to the `.attributes` dictionary attached to all ops: [ref1](https://github.com/google/jax/blob/30973a9474c44d06fa2edba8e200938dba739d64/jax/experimental/jax2tf/call_tf.py#L667), [more JAX examples](https://github.com/search?q=repo%3Agoogle%2Fjax+%22.attributes%5B%22&type=code).
Will need to have access to the op to call `.attributes`, can do this by walking the IR [example](https://github.com/llvm/llvm-project/blob/44be5a7fdc20a7f90d63dc18699a470e900bd3ba/mlir/test/python/ir/operation.py#L66).
2. Write an MLIR pass in C++ and add Python bindings, this is probably the more common approach, [ex: StablehloModule.cpp](https://github.com/openxla/stablehlo/blob/main/stablehlo/integrations/python/StablehloModule.cpp), or [_lower_to_llvm](https://github.com/karpathy/micrograd/pull/62/files#:~:text=def-,_lower_to_llvm) is a simple MLIR pass example in python. I believe the PT/XLA sharding you are looking at uses a C++ pass to add sharding (will double check).
3. Features in frameworks which can attach metadata while lowering to StableHLO. This is a framework dependent solution, I'm not actually sure if JAX/PTXLA allow for custom attrs to be defined on export though, will also look into this.

The way I see StableHLO evolving is by adding tooling which have Python bindings (tooling likely to be written in C++ given that's where MLIR is strongest). Things like "Here's a StableHLO program and a recipe, quantize or shard or something_else this program". In that sense, if there is a specific sort of tooling of interest, that would be good to know. If this is for something entirely custom, the above options are probably best.

**Comment by vincent-mayer** [comment]
Thanks for the detailed response and helpful links @GleasonK!
I believe pytorch-xla relies on XLA's infrastructure to set the attrs in their `hlo_to_mhlo` conversion, see [here](https://github.com/openxla/xla/blob/main/xla/translate/hlo_to_mhlo/hlo_module_importer.cc#L74-L100).

**Comment by kilianyp** [comment]
Thanks as well from my side @GleasonK, I will close this issue 🙇
