### ISSUE TITLE
Attributes missing in FuncInput spec

### ISSUE THREAD

**Issue by indhub** [openxla/stablehlo#2100]
### What happened?

In [spec.md](https://github.com/openxla/stablehlo/blob/main/docs/spec.md) FuncInput is defined as 

```
FuncInput   ::= ValueId ':' ValueType
ValueType    ::= TensorType | QuantizedTensorType | TokenType | TupleType
TensorType ::= 'tensor' '<' Shape TensorElementType '>'
```

But JAX produces this stable HLO

```
func.func public @main(%arg0: tensor<4xui32> {mhlo.layout_mode = "default", mhlo.sharding = "{replicated}", tf.aliasing_output = 0 : i32}, ...
```

Should the spec be modified to include attributes for FuncInput?

If yes, are the attributes same as `OpInputAttr`?

### Steps to reproduce your issue

1. Go to https://github.com/openxla/stablehlo/blob/main/docs/spec.md
2. Search for "FuncInput   ::="
3. See error

### Version information

dc4bc72de7e483adf7c3d5fac9b14bec526b10ef

**Comment by sdasgup3** [comment]
Hi @indhub 
Thanks for your feedback!

That is a valid point and  we do have plans for add (and.or refine) some if those function level attributes as part of
https://github.com/openxla/stablehlo/issues/425, https://github.com/openxla/stablehlo/issues/626, https://github.com/openxla/stablehlo/issues/740, https://github.com/openxla/stablehlo/issues/744.

**Comment by sdasgup3** [comment]
In the spec, we included only those attributes which are essential to define the semantics of the op or stablehlo program. This is one of the reason the above function input level attributes are not specified because  device sharding notations are unspecified in the spec.  

From the POV of op input-level attribute, we can see a few ops like unary ops and constant op takes optional input-level attributes, which, if specified, then used mostly for sharding or other back-end specific use-cases. Once we soecify some of those concepts,  we would like to revisited op input-level attributes as well.

**Comment by sdasgup3** [comment]
Please Let me know if this helps. 
Also, how about we close this issue. Instead we can continue out discussion in #744 ?

**Comment by indhub** [comment]
Yes, this is helpful. Thanks for those links.
