### ISSUE TITLE
Bump clang-format version in lint action

### ISSUE THREAD

**Issue by GleasonK** [openxla/stablehlo#2223]
### Request description

Looks like the runner is still using `clang-format-14`, which has some differences from more recent versions:

https://github.com/openxla/stablehlo/pull/2221/commits/06beb92f1aebc4892f53d5948a70512722cb3164

**Comment by mlevesquedion** [comment]
I discussed this with Kevin offline and I am of the opinion that under the current circumstances it is best to simply use the version of `clang-format` that is already available in the runner. We ran into some issues because we had a different (much more recent) version of clang-format installed, however that version of clang-format is not available in most standard package repositories and I don't think adding a PPA or building from source are reasonable options.

Instead, I opted to make the error message for formatting failures more helpful: https://github.com/openxla/stablehlo/pull/2330

If you want to avoid running into formatting errors in CI, consider running clang-format (be sure to use the right version) on save or in a pre-commit or pre-push hook, e.g. using `./build_tools/github_actions/lint_clang_format.sh -f`.
