### ISSUE TITLE
`broadcast_dimensions` of BroadcastInDimOp must be unique

### ISSUE THREAD

**Issue by sdasgup3** [openxla/stablehlo#277]
### Request description

Currently, we are not checking if the `broadcast_dimensions` in unique. Thereby passing

```
func.func @main(%operand: tensor<1x2xi32>) -> tensor<4x2x2xi32> {
  %result = "stablehlo.broadcast_in_dim"(%operand) {
  broadcast_dimensions = dense<[1, 1]>: tensor<2xi64>
 } : (tensor<1x2xi32>) -> tensor<4x2x2xi32>

  func.return %result : tensor<4x2x2xi32>
}
```

Just an FYI: The [HLO semantics](https://github.com/tensorflow/tensorflow/blob/c952f2758589a48e66a0bb84023a8fab0a47e948/tensorflow/compiler/xla/service/shape_inference.cc#L3074) is more strict on these dimensions

**Comment by burmako** [comment]
"Currently, we are not checking if the broadcast_dimensions in unique". In order to be aligned with HLO, it looks like we should not only check that the dimensions are unique but also that they are sorted? (Unless I misunderstood the purpose of this ticket, in which case I'll restore the old title).

**Comment by burmako** [comment]
After having reviewed #284, I'm realizing that I was too hasty to change the title of the ticket. This is a situation where MHLO semantics is materially different from HLO semantics, and #284 proposes to codify MHLO semantics into a spec. From that perspective, this ticket is comprehensive.
