### ISSUE TITLE
Support FP8

### ISSUE THREAD

**Issue by reedwm** [openxla/stablehlo#447]
### Request description

I proposed [an RFC](https://github.com/openxla/xla/discussions/22) for supporting FP8 to StableHLO and XLA. This issue tracks the effort to add the FP8 dtype to StableHLO.

/CC @burmako

**Comment by burmako** [comment]
Thank you for bringing this up! At the moment, we don't have a well-defined StableHLO RFC process (#196 is still in the works), so we might as well piggyback on the [FP8 in XLA RFC](https://github.com/openxla/xla/discussions/22) in this case.

Once there is an outcome of the XLA RFC, let's come back to this issue and decide accordingly. As long as there is consensus, the actual changes in StableHLO are going to be easy - just add a new element type in the "Types" section of the spec and in the definition of `HLO_Tensor` in the dialect.

**Comment by burmako** [comment]
We have just landed support for `f8E4M3FN` and `f8E5M2` element types in MHLO: https://github.com/tensorflow/mlir-hlo/commit/f9d277f903d20ca4a5af20c9088d9ce413d33dbc to start experimenting with FP8 support in XLA. Once/if the FP8 RFC is approved, we'll make a similar change to the StableHLO dialect.

**Comment by burmako** [comment]
The review period for the FP8 RFC has been extended to December 9. To quote @reedwm, "You are free to comment after that date but we may not be able to take into account your feedback. If there are no major objections to the design by that date, we will consider the RFC approved, otherwise we will schedule a design review meeting" ([full comment](https://github.com/openxla/xla/discussions/22#discussioncomment-4179254)).

**Comment by burmako** [comment]
The OpenXLA RFC has been approved yesterday. Will work on adding the corresponding FP8 types to StableHLO shortly.
