### ISSUE TITLE
Only allow float and complex element types in Atan2Op

### ISSUE THREAD

**Issue by ghpvnist** [openxla/stablehlo#499]
Currently the ODS accepts all element types, but there is no verification to only allow floating-point and complex types.

**Comment by sdasgup3** [comment]
As part of it we need to explore if atan2 is even defined for non float/complex element types. This is because the HLO verfier allows it and the evaluator says unimplemented https://github.com/tensorflow/tensorflow/blob/463d656802b67b377266b68d4b75db6bf8462f2b/tensorflow/compiler/xla/hlo/evaluator/hlo_evaluator_typed_visitor.h#L558.

**Comment by ghpvnist** [comment]
> As part of it we need to explore if atan2 is even defined for non float/complex element types. This is because the HLO verfier allows it and the evaluator says unimplemented.

The rationale behind why integers aren't supported is that it's not helpful to compute the atan2 (2-argument arctangent) that calculates the angle of (y, x), for which in most cases result in decimal values. As for whether complex is supported, it is allowed. The link you mentioned would be for booleans and integers:
https://github.com/tensorflow/tensorflow/blob/463d656802b67b377266b68d4b75db6bf8462f2b/tensorflow/compiler/xla/hlo/evaluator/hlo_evaluator_typed_visitor.h#L541-L552

**Comment by burmako** [comment]
As discussed in #500, we might also want to support integers here, depending on the outcome of the conversation on the pull request.
