### ISSUE TITLE
Modify clang-format to match the current state of the repository

### ISSUE THREAD

**Issue by GleasonK** [openxla/stablehlo#75]
### Request description

Currently the Lint action validates google syntax, while the `.clang-format` file specifies `LLVM`.

This is because it is based on TensorFlow's mhlo configuration:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/compiler/xla/mlir_hlo/.clang-format

However, for some reason `mlir-hlo` doesn't seem to use LLVM formatting uniformly, it uses google formatting. Note the "two spaces between code and comment:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/compiler/xla/mlir_hlo/lib/Dialect/mhlo/IR/hlo_ops.cc#L84 

Given this, we should use google formatting in the short term. 

In the near future we should resolve #15, as the longer we wait to change a coding style (if required), the more merge conflicts there will be.

**Comment by joker-eph** [comment]
> Given this, we should likely use google formatting in the short term, and consider flipping the repo to LLVM formatting at a later date. This requires edits to almost every cpp/h file in stablehlo which will cause merge conflicts.

How will this get better? Wouldn't we have less merge conflicts while doing it ASAP before we get many many PRs and the codebase get larger?

**Comment by burmako** [comment]
"How will this get better?". I read Kevin's comment not as a suggestion that this will get better, but rather that we should update `.clang-format` to reflect reality and have a discussion about which code style we want to follow (#15)

**Comment by joker-eph** [comment]
Well I was reacting to the part about "consider flipping the repo to LLVM formatting at a later date"

**Comment by GleasonK** [comment]
Both reasonable. I edited the issue title and description. Mehdi's comment does note a bit more urgency required by #15, the longer we wait, the more intrusive it will be to make any edits, if required. In the meantime, I'll modify the clang format to reflect the current state of this repo.

**Comment by joker-eph** [comment]
Here is what the opposite would look like FYI: https://github.com/openxla/stablehlo/pull/76 (so that we don't talk in hypothetical)

**Comment by GleasonK** [comment]
This is a tradeoff between consistency with MHLO and a preference to use LLVM formatting. Will it cause issues during integrations if the two have different formatting? I think that's the main thing I want to avoid.

**Comment by burmako** [comment]
"Will it cause issues during integrations if the two have different formatting?". Without revealing the details of how Google's internal process works, in the near future StableHLO will no longer be vendored in the TensorFlow repo (https://github.com/google/jax/pull/12174 is the externally visible tip of the iceberg), so we'll be able to have two different tooling configurations between the StableHLO repo and the TensorFlow repo.

This still leaves the question of handling code sharing between StableHLO and MHLO if they are going to have different code style. Right now, code sharing is handled by copy/pasting which is obviously inadequate, so this isn't a strong argument against choosing a different code style for StableHLO, because I imagine our eventual solution to code sharing won't be sensitive to stylistic differences.
