### ISSUE TITLE
Disable shape functions for ConvolutionOp and DotOp

### ISSUE THREAD

**Issue by zhouxin913** [openxla/stablehlo#778]
For many ops, not all components of return type can be inferred, for example,
- The return element type of DotOp / DotGeneralOp
- The return shape of ReshapeOp / RngBitGeneratorOp 

We could add the type inference in ODS, with a less restricted isCompatibleReturnTypes() which only checks the compatibility of some components while ignoring others. However, this will crash the auto generated Python API and JAX. So that we should only implement verifiers for this ops and call the shape function if needed instead.

**Comment by burmako** [comment]
"However, this will crash the auto generated Python API and JAX". To elaborate on this: these APIs will not crash, but they will be unusable from JAX because they produce wrong results (since e.g. shape functions for ConvolutionOp, DotOp and DotGeneralOp don't take preferred element type into account).

**Comment by ghpvnist** [comment]
With migrating MHLO changes to StableHLO and some StableHLO changes migrating to HLO, there is a conflict with a negative test for DotOp's precision_config verification. #780 removes this test, which may be added later once this lands.
